<a href="https://colab.research.google.com/github/Yesh287/Basic-Ml/blob/main/Regression_and_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import math as math

def sigmoid(z):
  return 1/(1+np.exp(-z))

def cost(x,y,w,b):
  total_cost = 0
  n,m = x.shape
  for i in range(n):
    prediction = sigmoid(np.dot(x[i],w)+b)
    total_cost += (prediction-y[i])**2
  return total_cost/n

def gradient_descent(x,y,w,b):
  n,m = x.shape
  dj_dw = np.zeros(m)
  dj_db = np.array(0.0)
  for i in range(n):
    z = np.dot(x[i], w) + b
    pred = sigmoid(z)
    err = pred - y[i]
    dj_dw += err*x[i]
    dj_db += err
  dj_dw /= n
  dj_db /= n
  return dj_dw, dj_db

def gradient_iteration(x,y,w,b,alpha,iterations):
  n,m = x.shape
  for i in range(iterations):
    dj_dw, dj_db = gradient_descent(x,y,w,b)
    w -= alpha*dj_dw
    b -= dj_db
    if((i)%math.ceil(iterations/10) == 0):
      print(w)
      print(cost(x,y,w,b))

w = np.zeros(3)
x = np.array([[1,2,3],
              [0,0,0],
              [0.1,0,0],
               [100,10,5],
                [2,2,2]])
y = np.array([1,0,0,1,1])
b = np.array(0.0)
alpha = 0.2
iterations = 10000
gradient_iteration(x,y,w,b,alpha,iterations)

[2.058 0.28  0.2  ]
0.12169425991635882
[2.71308534 1.51062743 1.90992681]
9.885471701539515e-06
[2.84327201 1.72811715 2.20058339]
2.4796379373871506e-06
[2.92168801 1.85614147 2.36988625]
1.1041199391639963e-06
[2.97833767 1.94731605 2.489649  ]
6.220269770438377e-07
[3.02285744 2.01822734 2.58233158]
3.986425368192143e-07
[3.05960778 2.07628859 2.6579187 ]
2.7717897010872157e-07
[3.09094246 2.12546402 2.72172759]
2.0387385917215813e-07
[3.11827995 2.16812454 2.77692757]
1.562556070455362e-07
[3.14254261 2.20580195 2.82556035]
1.2358254245784546e-07
